In [1]:
import numpy as np
from evaluation import gap, disparate_impact, evaluate

In [2]:
def read_data(filename):
    l = []
    with open(filename, 'r') as f:
        for line in f:
            l.append(line.strip())
    return l

In [3]:
f1 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss_2/Meta-Llama-3-8B-Instruct/result_0.01.txt')
f2 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss_2/Meta-Llama-3-8B-Instruct/result_0.02.txt')
f3 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss_2/Meta-Llama-3-8B-Instruct/result_0.03.txt')
f4 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss_2/Meta-Llama-3-8B-Instruct/result_0.04.txt')
true = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss/Meta-Llama-3-8B-Instruct/true.txt')


In [4]:
def valid_data(pred, true):
    valid_categories = {'White', 'Black', 'API', 'Hispanic'}
    filtered_predictions = []
    filtered_true_labels = []
    # Filter predictions and true labels
    for pred, true in zip(pred, true):
        if pred in valid_categories:
            filtered_predictions.append(pred)
            filtered_true_labels.append(true)
    return filtered_predictions, filtered_true_labels
    

In [5]:
ff1, ftrue1 = valid_data(f1, true)
ff2, ftrue2 = valid_data(f2, true)
ff3, ftrue3 = valid_data(f3, true)
ff4, ftrue4 = valid_data(f4, true)


In [6]:
for y_true, y_pred in zip([ftrue1, ftrue2, ftrue3, ftrue4], [ff1, ff2, ff3, ff4]):
    print('-------------------\n')
    evaluate(y_true, y_pred)
    gap(y_true, y_pred)
    disparate_impact(y_true, y_pred)

-------------------

Accuracy: 0.707

Classification Report:
              precision    recall  f1-score   support

         API       0.50      0.00      0.01       501
       Black       0.32      0.51      0.39      3712
    Hispanic       0.72      0.89      0.80      4258
       White       0.86      0.72      0.79     17405

    accuracy                           0.71     25876
   macro avg       0.60      0.53      0.50     25876
weighted avg       0.75      0.71      0.72     25876


Confusion Matrix:
[[    2   224    81   194]
 [    1  1897   228  1586]
 [    0   173  3774   311]
 [    1  3669  1123 12612]]
1-GAP:  0.8389
Disparate Impact is: 0.6446
-------------------

Accuracy: 0.492


/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavi


Classification Report:
              precision    recall  f1-score   support

         API       0.00      0.00      0.00       506
       Black       0.14      0.14      0.14      3671
    Hispanic       0.17      0.21      0.19      4202
       White       0.67      0.65      0.66     17171

    accuracy                           0.49     25550
   macro avg       0.25      0.25      0.25     25550
weighted avg       0.50      0.49      0.50     25550


Confusion Matrix:
[[    0    73   106   327]
 [    0   529   747  2395]
 [    0   594   879  2729]
 [    0  2455  3549 11167]]
1-GAP:  0.9992
Disparate Impact is: 0.1811
-------------------

Accuracy: 0.593


/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavi


Classification Report:
              precision    recall  f1-score   support

         API       0.00      0.00      0.00       510
       Black       0.18      0.01      0.02      3692
    Hispanic       0.19      0.20      0.19      4237
       White       0.68      0.83      0.75     17363

    accuracy                           0.59     25802
   macro avg       0.26      0.26      0.24     25802
weighted avg       0.51      0.59      0.54     25802


Confusion Matrix:
[[    0     2    74   434]
 [    0    30   601  3061]
 [    0    32   832  3373]
 [    0   107  2810 14446]]
1-GAP:  0.9915
Disparate Impact is: 0.0819
-------------------

Accuracy: 0.455

Classification Report:
              precision    recall  f1-score   support

         API       0.00      0.00      0.00       446
       Black       0.15      0.11      0.13      3260
    Hispanic       0.18      0.35      0.24      3767
       White       0.68      0.57      0.62     15269

    accuracy                         