In [1]:
import numpy as np
from evaluation import gap, disparate_impact, evaluate

In [2]:
def read_data(filename):
    l = []
    with open(filename, 'r') as f:
        for line in f:
            l.append(line.strip())
    return l

In [3]:
f1 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/new_loss_rank_32/Meta-Llama-3-8B-Instruct/lambada_1.0.txt')
f2 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/new_loss_rank_32/Meta-Llama-3-8B-Instruct/lambada_1.0.txt')
f3 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/rank_32/Meta-Llama-3-8B-Instruct/result_0.03.txt')
f4 = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss_2/Meta-Llama-3-8B-Instruct/result_0.04.txt')
true = read_data('/WAVE/projects/newsq_scu/xiaoxiao_git/Llama-race/logs/fair_loss/Meta-Llama-3-8B-Instruct/true.txt')


In [4]:
def valid_data(pred, true):
    valid_categories = {'White', 'Black', 'API', 'Hispanic'}
    filtered_predictions = []
    filtered_true_labels = []
    # Filter predictions and true labels
    for pred, true in zip(pred, true):
        if pred in valid_categories:
            filtered_predictions.append(pred)
            filtered_true_labels.append(true)
    return filtered_predictions, filtered_true_labels
    

In [5]:
ff1, ftrue1 = valid_data(f1, true)
ff2, ftrue2 = valid_data(f2, true)
ff3, ftrue3 = valid_data(f3, true)
ff4, ftrue4 = valid_data(f4, true)


In [6]:
for y_true, y_pred in zip([ftrue1, ftrue2, ftrue3, ftrue4], [ff1, ff2, ff3, ff4]):
    print('-------------------\n')
    evaluate(y_true, y_pred)
    gap(y_true, y_pred)
    disparate_impact(y_true, y_pred)

-------------------

Accuracy: 0.565

Classification Report:
              precision    recall  f1-score   support

         API       0.20      0.17      0.18       515
       Black       0.23      0.26      0.24      3719
    Hispanic       0.33      0.42      0.37      4262
       White       0.74      0.68      0.71     17436

    accuracy                           0.57     25932
   macro avg       0.38      0.38      0.38     25932
weighted avg       0.59      0.57      0.58     25932


Confusion Matrix:
[[   87    67   102   259]
 [   52   957   663  2047]
 [   50   533  1787  1892]
 [  242  2577  2785 11832]]
1-GAP:  0.9716
Disparate Impact is: 0.4153
-------------------

Accuracy: 0.431

Classification Report:
              precision    recall  f1-score   support

         API       0.14      0.07      0.09       515
       Black       0.17      0.43      0.24      3719
    Hispanic       0.28      0.28      0.28      4258
       White       0.71      0.48      0.57     17436

